name = "Journey MC"
author = "GameOnHunter"
version = "7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70c5a99171e66367416948428eeb2854750cb312a885af9f1b732d0395441748"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
