name = "Journey MC"
author = "GameOnHunter"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f975ee4833a2e8a154869bc1a0a487d75dfacec3c002ea5a2b8c328109b27b01"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
